name: ecom_shopping
description: The eCommerce Shopping app template for Android is an easy favorite. For those with an existing online shop, it enables easy conversion to a mobile store app, and for those who own a physical shop but don’t yet have an online store, eCommerce Shopping provides a variety of ready-to-use eCommerce Shopping mobile app templates to create a mobile store app from scratch. 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  firebase_dynamic_links: ^2.0.7
  share: ^2.0.4
  dio: ^4.0.0
  get: ^4.1.4
  shimmer: ^2.0.0
  photo_view: ^0.12.0
  flutter_appcenter_bundle: 3.2.0+2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_database: ^7.1.2
  firebase_messaging: ^10.0.4
  flutter_local_notifications: ^5.0.0+4
  chewie: ^1.2.2
  video_player: ^2.1.14
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0  

flutter_icons:
  image_path: 'assets/images/ecom_logo.png'
  image_path_android: 'assets/images/ecom_logo.png'
  android: true  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alef
      fonts:
        - asset: assets/fonts/Alef-Bold.ttf
          weight: 700
    - family: Alef-r
      fonts:
        - asset: assets/fonts/Alef-Regular.ttf      
      #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
